### PR TITLE
update to version 4.0.1 and add i18n support

### PR DESCRIPTION
**Pull request by bySabi**
Hi @nate-strauser please review this PR.
Thanks!

### CODE REVIEW

**Comment by nate-strauser** [comment]
it looks like you just deleted a whole bunch of files....

i think i need to redo this package to use a submodule that points to a fork of select2 with the problematic bits removed - how it is now, with the source files in the package, makes it difficult to do updates

**Comment by bySabi** [comment]
for update only need change version of npm package on `package.js`
A git submodule is not needed anymore.

**Comment by nate-strauser** [comment]
oh i see - that would work if we didn't need to customize select2 - see https://github.com/nate-strauser/meteor-select2/commit/7587946ba64437bbde96e598f38d44db1a0c9a7c

without removing that, spiderable will fail

**Comment by bySabi** [comment]
I see the problem.
Discard this PR then.
thanks.

**Pull request closed without merging**
